version: '3'

services:
  bot:
    image: bot
    container_name: bot
    env_file:
      - '.env'
    networks:
      - net
    depends_on:
      - db
      
  db:
    image: db
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - '.env'
    networks:
      - net

  db_repl:
    image: db_repl
    container_name: db_repl
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - '.env'
    networks:
      - net
    depends_on:
      - db

networks:
  net:
    driver: bridge
